### ISSUE TITLE
How to mute video

### ISSUE THREAD

**Issue by DebjitPramanick** [DeltaCircuit/react-media-recorder#102]
I was only able to mute audio. But not able to mute video while recording.

**Comment by lazuardi21** [comment]
what do you mean by mute the video?

**Comment by diazlp** [comment]
haha, you can just use the `audio: false` or probably can do this onto your video element tag

<video muted {...props}/>

**Comment by AshishDhama** [comment]
@DebjitPramanick I am closing this if you still need help please provide an example code or some clarifications on what you want to achieve so that the community can help you.
